pipeline {
  agent any

  stages {

    stage('Quality Check') {
      steps {
        echo 'Running Quality Gate'
      }
    }

    stage('Build') {
      steps {
        echo 'Build Successful'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deployed to AWS'
      }
    }

  }
}
